### PR TITLE
Create Colour v0.3.10 version.

### PR DESCRIPTION
**Pull request by KelSolaar**

### CODE REVIEW

**Comment by ocefpaf** [comment]
Re-rendering and #3 should fix the CIs here.

@conda-forge-admin, please rerender

**Comment by thomasmansencal** [comment]
@ocefpaf : It seems like one of the AppVeyor test is queued since a few hours now: https://ci.appveyor.com/project/conda-forge/colour-science-feedstock/build/1.0.10/job/iwy63jp70d2us9jy

**Comment by ocefpaf** [comment]
The AppVeyor failure here is unrelated the PR. Merging it.

**Comment by thomasmansencal** [comment]
Thanks @ocefpaf!

**Comment by ocefpaf** [comment]
Thank you for the feedstock update!

**Pull request merged**
